import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

import { COOKIE_THEME } from '@/const'
import etcUtil from '@/utils/etc.util'
import { cookies } from 'next/headers'
import React from 'react'
import { AppAside } from './_components/AppAside'
import AppBottomAppBar from './_components/AppBottomAppBar'
import { AppTopAppBar } from './_components/AppTopAppBar'
import { EnsureProviders } from './_components/EnsureProviders'
import './globals.scss'

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: React.PropsWithChildren) {
  const cookieStore = await cookies()
  const isDarkMode = cookieStore.get(COOKIE_THEME)?.value === 'dark'
  const isExpandAside = cookieStore.get('x-expand-aside')?.value === 'true'

  return (
    <html
      lang='en'
      className={etcUtil.classNames(['h-full', { dark: isDarkMode }])}>
      <body
        className={`${notoSansKr.className} antialiased | h-full | text-slate-800 dark:text-white/95`}>
        <EnsureProviders>
          <div className='h-full | flex flex-col lg:flex-row lg:gap-[28px] lg:p-[24px] lg:pr-[0px] | bg-gray-100 dark:bg-zinc-800'>
            <AppTopAppBar isDarkMode={isDarkMode} />
            <AppAside
              isDarkMode={isDarkMode}
              isExpand={isExpandAside}
            />
            <main className='w-full h-full overflow-scroll flex-1'>
              <div className='min-h-[calc(100%-88px)] | p-[16px] lg:p-[0px]'>{props.children}</div>
              <AppBottomAppBar />
            </main>
          </div>
        </EnsureProviders>
      </body>
    </html>
  )
}
