import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

import etcUtil from '@/utils/etc.util'
import { cookies } from 'next/headers'
import React from 'react'
import { AppAside } from './_components/AppAside'
import { EnsureProviders } from './_components/EnsureProviders'
import './globals.scss'

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default async function RootLayout(props: React.PropsWithChildren) {
  const cookieStore = await cookies()
  const isDarkMode = cookieStore.get('x-theme')?.value === 'dark'

  return (
    <html
      lang='en'
      className={etcUtil.classNames({
        dark: isDarkMode,
      })}>
      <body className={`${notoSansKr.className} antialiased | text-slate-800 dark:text-white/95`}>
        <EnsureProviders>
          <div className='flex gap-[24px] p-[24px] | bg-gray-100 dark:bg-zinc-900'>
            <AppAside isDarkMode={isDarkMode} />
            <main className='w-full'>{props.children}</main>
          </div>
        </EnsureProviders>
      </body>
    </html>
  )
}
