import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

import '@/app/assets/styles/globals.scss'
import etcUtil from '@/app/utils/etc.util'
import { COOKIE_THEME } from '@/const'
import { cookies } from 'next/headers'
import { AppAside } from '../components/AppAside'
import AppBottomAppBar from '../components/AppBottomAppBar'
import EnsureAuth from '../components/EnsureAuth'
import { EnsureProviders } from '../components/EnsureProviders'
import ScrollRestorer from '../components/ScrollRestorer'
import { ViewTransitions } from '../components/ViewTransitions'

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
})

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
}

export default async function RootLayout(props: LayoutProps<'/'>) {
  const cookieStore = await cookies()

  const isDarkMode = cookieStore.get(COOKIE_THEME)?.value === 'dark'
  const isExpandAside = cookieStore.get('x-expand-aside')?.value === 'true'
  const accessToken = cookieStore.get('x-google-access-token')?.value ?? ''
  const refreshToken = cookieStore.get('x-google-refresh-token')?.value ?? ''

  return (
    <ViewTransitions rootPages={['/', '/todos', '/calendar', '/news', '/settings']}>
      <ScrollRestorer />
      <html
        lang='en'
        className={etcUtil.classNames(['h-full', { dark: isDarkMode }])}>
        <head>
          <meta
            name='theme-color'
            content='transparent'
          />
          <meta
            name='apple-mobile-web-app-capable'
            content='yes'></meta>
          <meta
            name='apple-mobile-web-app-status-bar-style'
            content='black-translucent'></meta>
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1, viewport-fit=cover'></meta>
        </head>
        <body
          className={`${notoSansKr.className} antialiased | h-full | text-slate-800 dark:text-white/95 | bg-gray-100 dark:bg-zinc-900`}>
          <EnsureAuth
            accessToken={accessToken}
            refreshToken={refreshToken}>
            <EnsureProviders isDarkMode={isDarkMode}>
              <div className='relative | h-full | flex flex-col sm:flex-row sm:gap-[36px] sm:p-[24px] sm:pr-[0]'>
                <AppAside isExpand={isExpandAside} />
                <main
                  id='scroll-el'
                  className='relative z-[1] | flex flex-col | w-full h-full overflow-auto flex-1 sm:pr-[24px] pb-[4px]'>
                  <div className='sm:h-full | flex flex-col | flex-1'>{props.children}</div>

                  <AppBottomAppBar />
                </main>
              </div>
            </EnsureProviders>
          </EnsureAuth>
        </body>
      </html>
    </ViewTransitions>
  )
}
